version: '3'

services:
  client: 
    image: node:16.15.0
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /client
    working_dir: /client
    command: bash -c "npm install && npm run dev"

  api:
    image: node:16.15.0
    ports:
      - 3000:3000
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=journals
      - COHORT=shaw
      - PGPORT=5432
    volumes:
      - type: bind
        source: ./api
        target: /server
    working_dir: /server
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=journals
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=password

volumes:
  dbdata:
